name: ReleaseByTags
on:
  push:
    tags:
      - '*'
jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ${{ github.workspace }}/publish.sh
      - uses: actions/upload-artifact@master
        with:
         name: publish-linux-binaries
         path: ${{ github.workspace }}/publish
  Build_Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ${{ github.workspace }}/publish.bat
      - uses: actions/upload-artifact@master
        with:
         name: publish-windows-binaries
         path: ${{ github.workspace }}/publish
  Deploy_Artifacts:
    needs: [Build_Linux,Build_Windows]
    runs-on: ubuntu-latest
    steps:
      - name: Restoring linux artifacts
        uses: actions/download-artifact@master
        with:
          path: ${{ github.workspace }}/publish
	  merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/publish/win10-x64.zip,${{ github.workspace }}/publish/debian.8-x64.zip,${{ github.workspace }}/publish/linux-arm.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
